name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_RUN_TARGET: ninja-single-debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Submodules
      run: |
        git submodule update --init deps/csv-parser
        git submodule update --init deps/vcpkg

    - name: Setup vcpkg env
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/deps/vcpkg'
        vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'
        runVcpkgInstall: true

    - name: CMake run
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{env.TEST_RUN_TARGET}}'
        buildPreset: '${{env.TEST_RUN_TARGET}}'

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ctest --test-dir ${{github.workspace}}/builds/${{env.TEST_RUN_TARGET}}/src/metsi-app --output-on-failure
        ctest --test-dir ${{github.workspace}}/builds/${{env.TEST_RUN_TARGET}}/src/metsi-simlib --output-on-failure

