name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_RUN_TARGET: ninja-release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Submodules
        run: git submodule update --init deps/vcpkg

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg env
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: ${{github.workspace}}/deps/vcpkg
          vcpkgJsonGlob: ${{github.workspace}}/vcpkg.json
          runVcpkgInstall: true

      - name: CMake configure
        run: cmake . -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/${{runner.os}}-installprefix --preset ${{env.TEST_RUN_TARGET}}

      - name: CMake build
        run: cmake --build builds/${{env.TEST_RUN_TARGET}}

      - name: metsi-simlib unit tests
        run: ctest --test-dir ${{github.workspace}}/builds/${{env.TEST_RUN_TARGET}}/metsi-simlib --output-on-failure

      - name: metsi-app unit tests
        run: ctest --test-dir ${{github.workspace}}/builds/${{env.TEST_RUN_TARGET}}/metsi-app --output-on-failure

      - name: CMake install
        run: cmake --install builds/${{env.TEST_RUN_TARGET}}

      - uses: actions/upload-artifact@v3
        with:
          name: metsi-${{runner.os}}
          path: ${{github.workspace}}/${{runner.os}}-installprefix/*